/*
 * addresses
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, text, boolean, index, foreignKey, serial, integer, doublePrecision, primaryKey } from 'drizzle-orm/pg-core';
import { users } from './user.model.js';

export const addresses = pgTable("addresses", {
	id: serial().primaryKey().notNull(),
	userId: integer("user_id").notNull(),
	fullName: text("full_name").notNull(),
	phone: text().notNull(),
	addressLine1: text("address_line1").notNull(),
	addressLine2: text("address_line2"),
	city: text().notNull(),
	state: text().notNull(),
	pincode: text().notNull(),
	latitude: doublePrecision(),
	longitude: doublePrecision(),
	isDefault: boolean("is_default").default(false).notNull(),
	label: text().default('Home').notNull(),
}, (table) => [
	index("addresses_user_id_idx").using("btree", table.userId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "addresses_user_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);
