/*
 * admin_accounts, admin_sessions
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, boolean, index, foreignKey, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';
import { sql } from 'drizzle-orm';

export const adminAccounts = pgTable("admin_accounts", {
	phone: text().primaryKey().notNull(),
	name: text(),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: tstz("created_at").default(sql`now()`).notNull(),
	lastLoginAt: tstz("last_login_at"),
});

export const adminSessions = pgTable("admin_sessions", {
	tokenHash: text("token_hash").primaryKey().notNull(),
	phone: text().notNull(),
	createdAt: tstz("created_at").notNull(),
	expiresAt: tstz("expires_at").notNull(),
	lastSeenAt: tstz("last_seen_at"),
	userAgent: text("user_agent"),
}, (table) => [
	index("idx_admin_sessions_phone").using("btree", table.phone.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.phone],
			foreignColumns: [adminAccounts.phone],
			name: "admin_sessions_phone_fkey"
		}).onDelete("cascade"),
]);
