/*
 * cart_items
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, foreignKey, serial, integer, primaryKey } from 'drizzle-orm/pg-core';
import { money } from './_columns.js';
import { cart } from './cart.model.js';
import { products } from './product.model.js';

export const cartItems = pgTable("cart_items", {
	id: serial().primaryKey().notNull(),
	cartId: integer("cart_id").notNull(),
	productId: integer("product_id").notNull(),
	quantity: integer().notNull(),
	selectedOptions: text("selected_options"),
	unitPrice: money("unit_price", { precision: 12, scale:  2 }).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.cartId],
			foreignColumns: [cart.id],
			name: "cart_items_cart_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "cart_items_product_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);
