/*
 * cart
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, foreignKey, serial, integer, unique, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';
import { users } from './user.model.js';

export const cart = pgTable("cart", {
	id: serial().primaryKey().notNull(),
	userId: integer("user_id").notNull(),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "cart_user_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	unique("cart_user_id_key").on(table.userId),
]);
