/*
 * contact_messages
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, boolean, serial, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';

export const contactMessages = pgTable("contact_messages", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	phone: text(),
	message: text().notNull(),
	handled: boolean().default(false).notNull(),
	createdAt: tstz("created_at").notNull(),
});
