/*
 * coupons
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, boolean, foreignKey, serial, integer, unique, primaryKey } from 'drizzle-orm/pg-core';
import { money, dateOnly } from './_columns.js';
import { products } from './product.model.js';

export const coupons = pgTable("coupons", {
	id: serial().primaryKey().notNull(),
	code: text().notNull(),
	discountType: text("discount_type").notNull(),
	discountValue: money("discount_value", { precision: 12, scale:  2 }).notNull(),
	minimumOrderAmount: money("minimum_order_amount", { precision: 12, scale:  2 }),
	maximumDiscount: money("maximum_discount", { precision: 12, scale:  2 }),
	expiryDate: dateOnly("expiry_date"),
	usageLimit: integer("usage_limit"),
	isActive: boolean("is_active").default(true).notNull(),
	spinWeight: money("spin_weight", { precision: 6, scale:  3 }),
	spinLabel: text("spin_label"),
	terms: text(),
	giftKind: text("gift_kind"),
	giftProductId: integer("gift_product_id"),
}, (table) => [
	foreignKey({
			columns: [table.giftProductId],
			foreignColumns: [products.id],
			name: "coupons_gift_product_id_fkey"
		}).onDelete("set null"),
	unique("coupons_code_key").on(table.code),
]);
