/*
 * coupon_usage
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, foreignKey, serial, integer, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';
import { coupons } from './coupon.model.js';
import { orders } from './order.model.js';
import { users } from './user.model.js';

export const couponUsage = pgTable("coupon_usage", {
	id: serial().primaryKey().notNull(),
	couponId: integer("coupon_id").notNull(),
	userId: integer("user_id").notNull(),
	orderId: integer("order_id").notNull(),
	usedAt: tstz("used_at").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.couponId],
			foreignColumns: [coupons.id],
			name: "coupon_usage_coupon_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "coupon_usage_order_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "coupon_usage_user_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
]);
