/*
 * orders
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, boolean, index, foreignKey, serial, integer, unique, primaryKey } from 'drizzle-orm/pg-core';
import { money, tstz } from './_columns.js';
import { addresses } from './address.model.js';
import { storeUsers } from './store.model.js';
import { users } from './user.model.js';

export const orders = pgTable("orders", {
	id: serial().primaryKey().notNull(),
	orderNumber: text("order_number").notNull(),
	userId: integer("user_id").notNull(),
	addressId: integer("address_id"),
	subtotal: money({ precision: 12, scale:  2 }).notNull(),
	discountAmount: money("discount_amount", { precision: 12, scale:  2 }).default(0).notNull(),
	deliveryFee: money("delivery_fee", { precision: 12, scale:  2 }).default(0).notNull(),
	taxAmount: money("tax_amount", { precision: 12, scale:  2 }).default(0).notNull(),
	totalAmount: money("total_amount", { precision: 12, scale:  2 }).notNull(),
	couponCode: text("coupon_code"),
	paymentStatus: text("payment_status").default('PENDING').notNull(),
	orderStatus: text("order_status").default('PLACED').notNull(),
	delhiveryWaybill: text("delhivery_waybill"),
	delhiveryShipmentId: text("delhivery_shipment_id"),
	trackingUrl: text("tracking_url"),
	shipmentStatus: text("shipment_status").default('NOT_CREATED').notNull(),
	labelGenerated: boolean("label_generated").default(false).notNull(),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
	razorpayOrderId: text("razorpay_order_id"),
	carrier: text(),
	estimatedDelivery: text("estimated_delivery"),
	carrierOrderId: text("carrier_order_id"),
	shipmentError: text("shipment_error"),
	storeCode: text("store_code"),
	storeAcceptedAt: tstz("store_accepted_at"),
	storeAcceptedBy: integer("store_accepted_by"),
	storeReadyAt: tstz("store_ready_at"),
	storePosBillNo: text("store_pos_bill_no"),
	riderRetryCount: integer("rider_retry_count").default(0).notNull(),
	riderRetryAt: tstz("rider_retry_at"),
}, (table) => [
	index("idx_orders_store_code").using("btree", table.storeCode.asc().nullsLast().op("text_ops")),
	index("orders_user_id_idx").using("btree", table.userId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.addressId],
			foreignColumns: [addresses.id],
			name: "orders_address_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
	foreignKey({
			columns: [table.storeAcceptedBy],
			foreignColumns: [storeUsers.id],
			name: "orders_store_accepted_by_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "orders_user_id_fkey"
		}).onUpdate("cascade").onDelete("restrict"),
	unique("orders_order_number_key").on(table.orderNumber),
]);
