/*
 * order_tracking
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, text, foreignKey, serial, integer, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';
import { orders } from './order.model.js';

export const orderTracking = pgTable("order_tracking", {
	id: serial().primaryKey().notNull(),
	orderId: integer("order_id").notNull(),
	status: text().notNull(),
	remarks: text(),
	createdAt: tstz("created_at").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "order_tracking_order_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);
