/*
 * order_items
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, index, foreignKey, serial, integer, primaryKey } from 'drizzle-orm/pg-core';
import { money } from './_columns.js';
import { orders } from './order.model.js';
import { products } from './product.model.js';

export const orderItems = pgTable("order_items", {
	id: serial().primaryKey().notNull(),
	orderId: integer("order_id").notNull(),
	productId: integer("product_id"),
	productName: text("product_name").notNull(),
	quantity: integer().notNull(),
	unitPrice: money("unit_price", { precision: 12, scale:  2 }).notNull(),
	totalPrice: money("total_price", { precision: 12, scale:  2 }).notNull(),
	selectedOptions: text("selected_options"),
	specialNotes: text("special_notes"),
}, (table) => [
	index("order_items_order_id_idx").using("btree", table.orderId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "order_items_order_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "order_items_product_id_fkey"
		}).onUpdate("cascade").onDelete("set null"),
]);
