/*
 * payments
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, text, index, foreignKey, serial, integer, primaryKey } from 'drizzle-orm/pg-core';
import { money, tstz } from './_columns.js';
import { orders } from './order.model.js';

export const payments = pgTable("payments", {
	id: serial().primaryKey().notNull(),
	orderId: integer("order_id").notNull(),
	provider: text().notNull(),
	transactionId: text("transaction_id"),
	amount: money({ precision: 12, scale:  2 }).notNull(),
	status: text().notNull(),
	paidAt: tstz("paid_at"),
	createdAt: tstz("created_at").notNull(),
	razorpayFee: money("razorpay_fee", { precision: 12, scale:  2 }),
	razorpayTax: money("razorpay_tax", { precision: 12, scale:  2 }),
	method: text(),
	cardNetwork: text("card_network"),
	cardLast4: text("card_last4"),
	vpa: text(),
	bank: text(),
	amountRefunded: money("amount_refunded", { precision: 12, scale:  2 }).default('0').notNull(),
}, (table) => [
	index("payments_order_id_idx").using("btree", table.orderId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "payments_order_id_fkey"
		}).onUpdate("cascade").onDelete("cascade"),
]);
