/*
 * petpooja_items, petpooja_orders, petpooja_taxes, petpooja_addons, petpooja_stores, petpooja_menu_snapshots
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 *
 * Their menu, mirrored. Prices here are theirs and are an id source only — what we charge lives on
 * our own products table, which is why nothing reads price from these rows.
 */
import { pgTable, text, boolean, foreignKey, serial, integer, unique, jsonb, primaryKey } from 'drizzle-orm/pg-core';
import { money, tstz } from './_columns.js';
import { orders } from './order.model.js';
import { products } from './product.model.js';

export const petpoojaItems = pgTable("petpooja_items", {
	id: serial().primaryKey().notNull(),
	restId: text("rest_id").notNull(),
	itemId: text("item_id").notNull(),
	variationId: text("variation_id").default('').notNull(),
	name: text().notNull(),
	variationName: text("variation_name"),
	price: money({ precision: 12, scale:  2 }),
	categoryId: text("category_id"),
	taxIds: text("tax_ids"),
	inStock: boolean("in_stock").default(true).notNull(),
	productId: integer("product_id"),
	raw: jsonb(),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "petpooja_items_product_id_fkey"
		}).onDelete("set null"),
	unique("petpooja_items_rest_id_item_id_variation_id_key").on(table.restId, table.itemId, table.variationId),
]);

export const petpoojaOrders = pgTable("petpooja_orders", {
	id: serial().primaryKey().notNull(),
	orderId: integer("order_id").notNull(),
	restId: text("rest_id").notNull(),
	relayOk: boolean("relay_ok").default(false).notNull(),
	petpoojaOrderId: text("petpooja_order_id"),
	petpoojaStatus: text("petpooja_status"),
	attempts: integer().default(0).notNull(),
	request: jsonb(),
	response: jsonb(),
	lastError: text("last_error"),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.orderId],
			foreignColumns: [orders.id],
			name: "petpooja_orders_order_id_fkey"
		}).onDelete("cascade"),
	unique("petpooja_orders_order_id_key").on(table.orderId),
]);

export const petpoojaTaxes = pgTable("petpooja_taxes", {
	id: serial().primaryKey().notNull(),
	restId: text("rest_id").notNull(),
	taxId: text("tax_id").notNull(),
	name: text().notNull(),
	percentage: money({ precision: 6, scale:  3 }).default('0').notNull(),
	taxType: text("tax_type"),
	raw: jsonb(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	unique("petpooja_taxes_rest_id_tax_id_key").on(table.restId, table.taxId),
]);

export const petpoojaAddons = pgTable("petpooja_addons", {
	id: serial().primaryKey().notNull(),
	restId: text("rest_id").notNull(),
	addonId: text("addon_id").notNull(),
	groupId: text("group_id"),
	groupName: text("group_name"),
	name: text().notNull(),
	price: money({ precision: 12, scale:  2 }).default('0').notNull(),
	inStock: boolean("in_stock").default(true).notNull(),
	raw: jsonb(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	unique("petpooja_addons_rest_id_addon_id_key").on(table.restId, table.addonId),
]);

export const petpoojaStores = pgTable("petpooja_stores", {
	restId: text("rest_id").primaryKey().notNull(),
	storeStatus: boolean("store_status").default(true).notNull(),
	turnOnTime: text("turn_on_time"),
	reason: text(),
	updatedAt: tstz("updated_at").notNull(),
});

export const petpoojaMenuSnapshots = pgTable("petpooja_menu_snapshots", {
	id: serial().primaryKey().notNull(),
	restId: text("rest_id").notNull(),
	source: text().notNull(),
	payload: jsonb().notNull(),
	itemCount: integer("item_count").default(0).notNull(),
	receivedAt: tstz("received_at").notNull(),
});
