/*
 * products
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, text, boolean, serial, integer, primaryKey } from 'drizzle-orm/pg-core';
import { money, tstz } from './_columns.js';

export const products = pgTable("products", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	category: text().notNull(),
	description: text(),
	price: money({ precision: 12, scale:  2 }).notNull(),
	stockQuantity: integer("stock_quantity").default(0).notNull(),
	images: text(),
	options: text(),
	isAvailable: boolean("is_available").default(true).notNull(),
	menuGroup: text("menu_group"),
	tag: text(),
	featured: boolean().default(false).notNull(),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
	restrictCities: text("restrict_cities"),
	intracityAvailable: boolean("intracity_available").default(true).notNull(),
	intracityUnavailableReason: text("intracity_unavailable_reason"),
	intercityAvailable: boolean("intercity_available").default(true).notNull(),
	intercityUnavailableReason: text("intercity_unavailable_reason"),
});
