/*
 * site_settings
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, primaryKey } from 'drizzle-orm/pg-core';

export const siteSettings = pgTable("site_settings", {
	key: text().primaryKey().notNull(),
	value: text(),
});
