/*
 * spin_claims, spin_draws, spin_ticket_pool, spin_email_claims
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 */
import { pgTable, text, index, foreignKey, serial, integer, uniqueIndex, check, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';
import { sql } from 'drizzle-orm';
import { coupons } from './coupon.model.js';
import { products } from './product.model.js';
import { users } from './user.model.js';

export const spinClaims = pgTable("spin_claims", {
	id: serial().primaryKey().notNull(),
	userId: integer("user_id").notNull(),
	couponId: integer("coupon_id").notNull(),
	code: text().notNull(),
	label: text().notNull(),
	claimedAt: tstz("claimed_at").notNull(),
	expiresAt: tstz("expires_at").notNull(),
	giftProductId: integer("gift_product_id"),
}, (table) => [
	foreignKey({
			columns: [table.couponId],
			foreignColumns: [coupons.id],
			name: "spin_claims_coupon_id_fkey"
		}),
	foreignKey({
			columns: [table.giftProductId],
			foreignColumns: [products.id],
			name: "spin_claims_gift_product_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "spin_claims_user_id_fkey"
		}).onDelete("cascade"),
]);

export const spinDraws = pgTable("spin_draws", {
	id: serial().primaryKey().notNull(),
	deviceId: text("device_id").notNull(),
	userId: integer("user_id"),
	code: text(),
	drawnAt: tstz("drawn_at").notNull(),
	expiresAt: tstz("expires_at").notNull(),
	ip: text(),
}, (table) => [
	index("idx_spin_draws_device_id").using("btree", table.deviceId.asc().nullsLast().op("text_ops")),
	index("idx_spin_draws_ip").using("btree", table.ip.asc().nullsLast().op("text_ops")),
	index("idx_spin_draws_user_id").using("btree", table.userId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.userId],
			foreignColumns: [users.id],
			name: "spin_draws_user_id_fkey"
		}).onDelete("set null"),
]);

export const spinTicketPool = pgTable("spin_ticket_pool", {
	id: integer().default(1).primaryKey().notNull(),
	signature: text().notNull(),
	tickets: text().notNull(),
	position: integer().default(0).notNull(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	check("spin_ticket_pool_id_check", sql`id = 1`),
]);

export const spinEmailClaims = pgTable("spin_email_claims", {
	id: serial().primaryKey().notNull(),
	email: text().notNull(),
	name: text(),
	couponId: integer("coupon_id").notNull(),
	code: text().notNull(),
	label: text().notNull(),
	claimedAt: tstz("claimed_at").notNull(),
	expiresAt: tstz("expires_at").notNull(),
	linkedUserId: integer("linked_user_id"),
	giftProductId: integer("gift_product_id"),
}, (table) => [
	uniqueIndex("idx_spin_email_claims_email").using("btree", sql`lower(email)`),
	foreignKey({
			columns: [table.couponId],
			foreignColumns: [coupons.id],
			name: "spin_email_claims_coupon_id_fkey"
		}),
	foreignKey({
			columns: [table.giftProductId],
			foreignColumns: [products.id],
			name: "spin_email_claims_gift_product_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.linkedUserId],
			foreignColumns: [users.id],
			name: "spin_email_claims_linked_user_id_fkey"
		}).onDelete("set null"),
]);
