/*
 * store_users, store_status, store_product_overrides
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, text, boolean, index, foreignKey, serial, integer, unique, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';
import { products } from './product.model.js';

export const storeUsers = pgTable("store_users", {
	id: serial().primaryKey().notNull(),
	storeCode: text("store_code").notNull(),
	username: text().notNull(),
	passwordHash: text("password_hash").notNull(),
	name: text(),
	isActive: boolean("is_active").default(true).notNull(),
	lastLoginAt: tstz("last_login_at"),
	passwordSetAt: tstz("password_set_at"),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	index("idx_store_users_store_code").using("btree", table.storeCode.asc().nullsLast().op("text_ops")),
	unique("store_users_username_key").on(table.username),
]);

export const storeStatus = pgTable("store_status", {
	storeCode: text("store_code").primaryKey().notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	updatedAt: tstz("updated_at").notNull(),
	serviceMode: text("service_mode").default('BOTH').notNull(),
});

export const storeProductOverrides = pgTable("store_product_overrides", {
	storeCode: text("store_code").notNull(),
	productId: integer("product_id").notNull(),
	isAvailable: boolean("is_available").notNull(),
	updatedAt: tstz("updated_at").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.productId],
			foreignColumns: [products.id],
			name: "store_product_overrides_product_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.storeCode, table.productId], name: "store_product_overrides_pkey"}),
]);
