/*
 * users, password_reset_otps
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 *
 * password_reset_otps is DEAD — empty in production and referenced nowhere in src/. It is kept
 * here on purpose: models/ is what drizzle-kit diffs the database against, so a table left out of
 * it would be generated as a DROP on the next migration.
 */
import { pgTable, text, boolean, serial, unique, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';

export const users = pgTable("users", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	email: text(),
	phone: text(),
	password: text().notNull(),
	role: text().default('CUSTOMER').notNull(),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
	lastLoginLocation: text("last_login_location"),
}, (table) => [
	unique("users_email_key").on(table.email),
	unique("users_phone_key").on(table.phone),
]);

export const passwordResetOtps = pgTable("password_reset_otps", {
	id: serial().primaryKey().notNull(),
	email: text().notNull(),
	otp: text().notNull(),
	expiresAt: tstz("expires_at").notNull(),
	used: boolean().default(false).notNull(),
	createdAt: tstz("created_at").notNull(),
});
