/*
 * users, user_sessions, password_reset_otps
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.
 *
 * password_reset_otps is DEAD — empty in production and referenced nowhere in src/. It is kept
 * here on purpose: models/ is what drizzle-kit diffs the database against, so a table left out of
 * it would be generated as a DROP on the next migration.
 */
import { pgTable, text, boolean, serial, unique, primaryKey, uuid, integer, index } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';

export const users = pgTable("users", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	email: text(),
	phone: text(),
	password: text().notNull(),
	role: text().default('CUSTOMER').notNull(),
	createdAt: tstz("created_at").notNull(),
	updatedAt: tstz("updated_at").notNull(),
	lastLoginLocation: text("last_login_location"),
	/* Added by hand rather than by a drizzle-kit pull, against this file's own instructions,
	   because the alternative is worse: models/ is what drizzle-kit diffs the database against, so
	   a live column missing from here is generated as a DROP COLUMN on the next migration. That
	   would silently discard the link between our users and their Supabase auth accounts. Re-pull
	   and re-split when convenient; this keeps the diff honest until then. */
	supabaseUserId: uuid("supabase_user_id"),
}, (table) => [
	unique("users_email_key").on(table.email),
	unique("users_phone_key").on(table.phone),
	unique("users_supabase_user_id_key").on(table.supabaseUserId),
]);

/* Customer sessions — ours, not Supabase's. Added by hand for the same reason as
   users.supabase_user_id above: a live table missing from models/ is generated as a DROP, and
   dropping this one would sign every customer out. See services/userAuth.service.ts. */
export const userSessions = pgTable("user_sessions", {
	tokenHash: text("token_hash").primaryKey().notNull(),
	userId: integer("user_id").notNull().references(() => users.id, { onDelete: 'cascade' }),
	createdAt: tstz("created_at").notNull(),
	expiresAt: tstz("expires_at").notNull(),
	lastSeenAt: tstz("last_seen_at"),
	userAgent: text("user_agent"),
}, (table) => [
	index("idx_user_sessions_user").on(table.userId),
	index("idx_user_sessions_expires").on(table.expiresAt),
]);

export const passwordResetOtps = pgTable("password_reset_otps", {
	id: serial().primaryKey().notNull(),
	email: text().notNull(),
	otp: text().notNull(),
	expiresAt: tstz("expires_at").notNull(),
	used: boolean().default(false).notNull(),
	createdAt: tstz("created_at").notNull(),
});
