/*
 * warehouses
 *
 * Generated by scripts/split-models.mjs from a drizzle-kit pull of the live schema. Do not edit by
 * hand — change the database, pull, and re-split.

 */
import { pgTable, text, boolean, serial, varchar, primaryKey } from 'drizzle-orm/pg-core';
import { tstz } from './_columns.js';

export const warehouses = pgTable("warehouses", {
	id: serial().primaryKey().notNull(),
	name: varchar({ length: 255 }).notNull(),
	registeredName: varchar("registered_name", { length: 255 }),
	pickupLocation: varchar("pickup_location", { length: 255 }).notNull(),
	addressLine1: text("address_line1"),
	addressLine2: text("address_line2"),
	city: varchar({ length: 100 }),
	state: varchar({ length: 100 }),
	pincode: varchar({ length: 10 }).notNull(),
	phone: varchar({ length: 20 }),
	email: varchar({ length: 255 }),
	returnPincode: varchar("return_pincode", { length: 10 }),
	isActive: boolean("is_active").default(true).notNull(),
	isDefault: boolean("is_default").default(false).notNull(),
	createdAt: tstz("created_at").notNull(),
});
